"use client";
import { useEffect, useState } from 'react';
import { Plus, Send, Check, Mail, Mic } from 'lucide-react';
import { artisanRequest, listArtisanRecords, saveArtisanRecord, type Supplier } from '@/lib/artisan-records';
import { appendActivity, type CommercialDemoState, type CommercialCollaborator } from '@/lib/mobile-commercial-demo';
import { makeId } from '@/lib/mobile-prototype';
import { getActiveOrganizationId } from '@/lib/project-chapet';
type Contact = { email: string; address: string; notes: string };
const EMPTY_SUPPLIER: Supplier = { name:'',email:'',phone:'',address:'',contact:'',notes:'' };
export function CollaboratorPanel({state,onChange,onNotify}:{state:CommercialDemoState;onChange:(state:CommercialDemoState)=>void;onNotify:(message:string)=>void}) {
 const [draft,setDraft]=useState<CommercialCollaborator>({id:'',name:'',role:'',phone:'',initials:'',active:true});
 const [contact,setContact]=useState<Contact>({email:'',address:'',notes:''});
 const [contacts,setContacts]=useState<Record<string,Contact>>({});
 const [busy,setBusy]=useState(false);
 useEffect(()=>{listArtisanRecords<Contact>('collaborator_contact').then(rows=>setContacts(Object.fromEntries(rows.map(row=>[row.id,row.data])))).catch(error=>onNotify(error.message));},[]);
 async function save(){
  if(!draft.name.trim()){onNotify('Renseignez le nom du collaborateur.');return;}
  if(contact.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(contact.email)){onNotify('Adresse e-mail invalide.');return;}
  setBusy(true);
  const person={...draft,id:draft.id||makeId('collaborator'),name:draft.name.trim(),initials:draft.name.trim().split(/\s+/).map(word=>word[0]).slice(0,2).join('').toUpperCase()};
  try{await saveArtisanRecord('collaborator_contact',person.id,contact);onChange(appendActivity({...state,collaborators:[...state.collaborators.filter(item=>item.id!==person.id),person]},{kind:'data',message:`Fiche collaborateur ${person.name} enregistrée.`}));setContacts(current=>({...current,[person.id]:contact}));setDraft({id:'',name:'',role:'',phone:'',initials:'',active:true});setContact({email:'',address:'',notes:''});onNotify('Collaborateur enregistré.');}catch(error){onNotify(error instanceof Error?error.message:'Enregistrement impossible.');}finally{setBusy(false);}
 }
 async function invite(){if(!draft.id||!contact.email){onNotify('Ouvrez une fiche enregistrée avec son e-mail.');return;}setBusy(true);try{await artisanRequest('/api/team',{email:contact.email,role:'worker',organizationId:await getActiveOrganizationId()});onNotify('Invitation envoyée. Le collaborateur retrouve son compte sur ses appareils.');}catch(error){onNotify(error instanceof Error?error.message:'Invitation impossible.');}finally{setBusy(false);}}
 async function recover(){if(!contact.email){onNotify('Renseignez l’e-mail du compte.');return;}setBusy(true);try{await artisanRequest('/api/team/recovery',{email:contact.email});onNotify('Sessions révoquées et lien de récupération envoyé. Les données sont conservées.');}catch(error){onNotify(error instanceof Error?error.message:'Récupération impossible.');}finally{setBusy(false);}}
 return <div className="awp-body"><p>Les fiches sont sauvegardées dans votre entreprise. Un compte invité permet de retrouver ses données sur un autre téléphone.</p><div className="awp-list">{state.collaborators.map(person=><button key={person.id} onClick={()=>{setDraft(person);setContact(contacts[person.id]||{email:'',address:'',notes:''});}}><strong>{person.name}</strong><small>{person.role} · {person.phone || 'Téléphone à compléter'}</small></button>)}</div><h3>{draft.id?'Modifier le collaborateur':'Créer un collaborateur'}</h3><div className="awp-form"><label>Nom et prénom<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Métier / fonction<input value={draft.role} onChange={e=>setDraft({...draft,role:e.target.value})}/></label><label>Téléphone<input type="tel" value={draft.phone} onChange={e=>setDraft({...draft,phone:e.target.value})}/></label><label>E-mail<input type="email" value={contact.email} onChange={e=>setContact({...contact,email:e.target.value})}/></label><label>Adresse<input value={contact.address} onChange={e=>setContact({...contact,address:e.target.value})}/></label><label>Notes<textarea value={contact.notes} onChange={e=>setContact({...contact,notes:e.target.value})}/></label><button disabled={busy} onClick={()=>void save()}><Check size={18}/> Enregistrer la fiche</button>{draft.id&&<button disabled={busy} onClick={()=>void invite()}><Mail size={18}/> Inviter avec un accès terrain</button>}{draft.id&&<button disabled={busy} onClick={()=>void recover()}>Téléphone perdu : sécuriser et récupérer le compte</button>}</div><p>En cas de perte : reconnectez-vous avec le même e-mail ou utilisez « Mot de passe oublié ». L’administrateur peut révoquer l’accès de l’ancien appareil.</p></div>;
}
export function SupplierPanel({onNotify}:{onNotify:(message:string)=>void}){
 const [suppliers,setSuppliers]=useState<Array<{id:string;data:Supplier}>>([]);
 const [draft,setDraft]=useState<Supplier>(EMPTY_SUPPLIER);const [id,setId]=useState('');const [busy,setBusy]=useState(false);
 const [request,setRequest]=useState({supplierId:'',label:'',quantity:'',unit:'litres',targetPrice:'',notes:''});
 const [requestId,setRequestId]=useState('');
 useEffect(()=>{listArtisanRecords<Supplier>('supplier').then(setSuppliers).catch(error=>onNotify(error.message));},[]);
 async function save(){if(!draft.name.trim()||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(draft.email)){onNotify('Nom et e-mail du fournisseur requis.');return;}setBusy(true);const key=id||makeId('supplier');try{await saveArtisanRecord('supplier',key,draft);setSuppliers(current=>[...current.filter(item=>item.id!==key),{id:key,data:draft}]);setRequest(current=>({...current,supplierId:key}));setDraft(EMPTY_SUPPLIER);setId('');onNotify('Fournisseur enregistré.');}catch(error){onNotify(error instanceof Error?error.message:'Enregistrement impossible.');}finally{setBusy(false);}}
 async function send(){const quantity=Number(request.quantity.replace(',','.'));if(!request.supplierId||!request.label.trim()||quantity<=0){onNotify('Choisissez le fournisseur, le produit et la quantité.');return;}setBusy(true);const key=requestId||crypto.randomUUID();setRequestId(key);try{await artisanRequest('/api/suppliers/request-price',{supplierId:request.supplierId,requestId:key,label:request.label,quantity,unit:request.unit,targetPrice:request.targetPrice?Number(request.targetPrice.replace(',','.')):null,notes:request.notes});onNotify('Demande de prix envoyée au fournisseur.');setRequest({...request,label:'',quantity:'',targetPrice:'',notes:''});setRequestId('');}catch(error){onNotify(error instanceof Error?error.message:'Envoi impossible.');}finally{setBusy(false);}}
 function patchRequest(key:keyof typeof request,value:string){setRequest(current=>({...current,[key]:value}));setRequestId('');}
 return <div className="awp-body"><div className="awp-list">{suppliers.map(item=><button key={item.id} onClick={()=>{setDraft(item.data);setId(item.id);setRequest(current=>({...current,supplierId:item.id}));}}><strong>{item.data.name}</strong><small>{item.data.email} · {item.data.phone}</small></button>)}</div><h3>{id?'Modifier le fournisseur':'Créer un fournisseur'}</h3><div className="awp-form">{(['name','contact','email','phone','address'] as const).map(key=><label key={key}>{({name:'Entreprise',contact:'Contact',email:'E-mail',phone:'Téléphone',address:'Adresse'})[key]}<input type={key==='email'?'email':'text'} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}<button disabled={busy} onClick={()=>void save()}><Plus size={18}/>Enregistrer le fournisseur</button></div><h3>Demander un devis fournisseur</h3><div className="awp-form"><label>Fournisseur<select value={request.supplierId} onChange={e=>patchRequest('supplierId',e.target.value)}><option value="">Choisir</option>{suppliers.map(item=><option value={item.id} key={item.id}>{item.data.name}</option>)}</select></label>{(['label','quantity','unit','targetPrice','notes'] as const).map(key=><label key={key}>{({label:'Produit / travaux',quantity:'Quantité',unit:'Unité',targetPrice:'Prix unitaire souhaité HT (facultatif)',notes:'Livraison / précisions'})[key]}<input value={request[key]} onChange={e=>patchRequest(key,e.target.value)}/></label>)}<button disabled={busy} onClick={()=>void send()}><Send size={18}/>{busy?'Envoi…':'Envoyer la demande de prix'}</button><button onClick={()=>window.dispatchEvent(new CustomEvent('projetchapet:open-ai',{detail:{target:'command'}}))}><Mic size={18}/>Dicter une demande fournisseur</button></div><p>Le fournisseur reçoit une demande de prix, sans commande ferme.</p></div>;
}
export function InboundEmailPanel({onNotify}:{onNotify:(message:string)=>void}){
 const [form,setForm]=useState({sender:'',subject:'',body:''});const [busy,setBusy]=useState(false);const [result,setResult]=useState<{name:string;id:string}|null>(null);const [key,setKey]=useState('');
 async function importEmail(){if(!form.subject.trim()||!form.body.trim()){onNotify('Ajoutez l’objet et le contenu du mail.');return;}setBusy(true);const requestId=key||crypto.randomUUID();setKey(requestId);try{const data=await artisanRequest('/api/inbound-email/import',{...form,requestId});setResult(data.project);onNotify('Fiche chantier créée et sauvegardée.');window.dispatchEvent(new Event('manufeo:workspace-changed'));}catch(error){onNotify(error instanceof Error?error.message:'Import impossible.');}finally{setBusy(false);}}
 async function readMail(file:File|null){if(!file)return; if(file.size>200000){onNotify('Mail trop volumineux (200 Ko maximum).');return;}const text=await file.text();const parts=text.split(/\r?\n\r?\n/);const headers=parts.shift()||'';setForm({sender:headers.match(/^From:\s*(.*)$/im)?.[1]||'',subject:headers.match(/^Subject:\s*(.*)$/im)?.[1]||file.name,body:parts.join('\n\n')||text});setResult(null);setKey('');}
 return <div className="awp-body"><p>Copiez un mail reçu ou importez son fichier .eml. MANUFEO prépare une fiche chantier ; le devis reste à compléter et valider.</p><div className="awp-form"><label>Importer un e-mail<input type="file" accept=".eml,text/plain,message/rfc822" onChange={event=>void readMail(event.target.files?.[0]||null)}/></label><label>Expéditeur<input value={form.sender} onChange={e=>{setForm({...form,sender:e.target.value});setKey('');setResult(null);}}/></label><label>Objet<input value={form.subject} onChange={e=>{setForm({...form,subject:e.target.value});setKey('');setResult(null);}}/></label><label>Demande d’intervention<textarea rows={8} value={form.body} onChange={e=>{setForm({...form,body:e.target.value});setKey('');setResult(null);}}/></label><button disabled={busy||!!result} onClick={()=>void importEmail()}><Check size={18}/>{busy?'Création…':result?'Chantier créé':'Créer le chantier depuis ce mail'}</button></div>{result&&<p role="status"><strong>{result.name}</strong> : disponible dans Chantiers & équipe pour préparer le devis.</p>}</div>;
}
