"use client";
import { useEffect,useState } from 'react';
import { supabase } from '@/lib/supabase';
import { artisanRequest } from '@/lib/artisan-records';
type Workspace={projects:Array<{id:string;name:string;subtitle:string;address:string;status:string}>;steps:Array<{id:string;project_id:string;label:string;done:boolean}>;photos:Array<{id:string;project_id:string;caption:string;url:string}>};
export default function WorkerWorkspace(){
 const [workspace,setWorkspace]=useState<Workspace>({projects:[],steps:[],photos:[]}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const {data}=await supabase.auth.getSession();const response=await fetch('/api/worker-workspace',{headers:{Authorization:`Bearer ${data.session?.access_token}`}});const result=await response.json();if(!response.ok)throw new Error(result.error);setWorkspace(result);}catch(error){setError(error instanceof Error?error.message:'Chargement impossible.');}}
 useEffect(()=>{void load();},[]);
 async function update(body:object){setBusy(true);setError('');try{await artisanRequest('/api/worker-workspace',body);await load();}catch(error){setError(error instanceof Error?error.message:'Sauvegarde impossible.');}finally{setBusy(false);}}
 async function photo(projectId:string,file:File|null){if(!file)return;if(file.size>4000000){setError('Utilisez une photo de moins de 4 Mo.');return;}const reader=new FileReader();reader.onload=()=>void update({projectId,name:file.name,photo:String(reader.result)});reader.readAsDataURL(file);}
 return <main className="worker-app"><header><strong>MANUFEO · Mon équipe</strong><button onClick={()=>void load()}>Actualiser</button></header><p>Vos chantiers, consignes et photos sont sauvegardés dans votre compte.</p>{error&&<p role="alert">{error}</p>}{!workspace.projects.length&&<p>Aucun chantier affecté. Demandez à votre responsable de vous ajouter à l’équipe du chantier.</p>}{workspace.projects.map(project=><section key={project.id}><h2>{project.name}</h2><p>{project.address}</p><p>{project.subtitle}</p><strong>{project.status}</strong><div>{workspace.steps.filter(step=>step.project_id===project.id).map(step=><label key={step.id}><input type="checkbox" disabled={busy} checked={step.done} onChange={event=>void update({projectId:project.id,stepId:step.id,done:event.target.checked})}/>{step.label}{step.done?' · Terminé':''}</label>)}</div><div className="worker-photos">{workspace.photos.filter(photo=>photo.project_id===project.id).map(photo=><img key={photo.id} src={photo.url} alt={photo.caption}/>)}</div><label>Ajouter une photo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={event=>void photo(project.id,event.target.files?.[0]||null)}/></label></section>)}<style>{`.worker-app{max-width:1000px;margin:auto;padding:20px;font-family:Arial;color:#163954;min-height:100dvh;background:#f3f7fa}.worker-app header{display:flex;justify-content:space-between;align-items:center;gap:12px}.worker-app button{min-height:44px;border:0;border-radius:10px;background:#17674d;color:white;padding:12px}.worker-app section{padding:20px;margin:16px 0;border:1px solid #d8e2eb;border-radius:18px;background:white}.worker-app label{display:flex;gap:10px;align-items:center;padding:10px 0}.worker-photos{display:flex;gap:12px;overflow:auto}.worker-photos img{width:220px;height:180px;object-fit:cover;border-radius:12px}`}</style></main>;
}
